### ISSUE TITLE
Confusing misspelling in readme

### ISSUE THREAD

**Issue by iaminstanceof** [kevindurb/router#1]
I am talking about the last section of `README` - "Usage with history package".

This line:
```javascript
import { router, mountHistory } from '@kevindurb/router';
```

and this one:
```javascript
history.listen(mountHistory(app));
```

are uses non-existent export `mountHistory`: I've discovered source code and found that library are exposing `historyMount` function (reverse words order).

This mistake can push away those who are playing with a new library before an integration into something.

**Comment by kevindurb** [comment]
Whoops! Sorry! Released a fix in 1.0.2!
