### ISSUE TITLE
instance.resolve and instance.compose methods

### ISSUE THREAD

**Issue by tracker1** [kevindurb/router#2]
Would be nice to have a capturing resolve and compose methods exposed...  resolve would effectively return the matching route and parameters for a given url.

```
    instance.resolve('http://server/foo/some%20%2B%20id'); 
    // returns { route: '/foo/:id', params: { id: "some + id" } } - decodeURIComponent

    instance.compose('/foo/:id', { id: "some + id" });
    // return '/foo/some%20%2B%20id' - encodeURIComponent
```

**Comment by tracker1** [comment]
maybe a `instance.compose(url, params, queryString)` option for encoding the query string parameters too.

**Comment by kevindurb** [comment]
@tracker1 take a look at the dependancy of this project https://github.com/pillarjs/path-to-regexp . It is how i do `resolve` and i hesitate adding a function that does just what this does, but im totally good with it if theres a good use case. As for the `compose` that can be done with somewhat with node's `path.join()` but i do see how you would like to be able to possibly reuse the route strings? If you could give me some use case examples that would really help!

**Comment by iaminstanceof** [comment]
(I am sorry for interruption but there`s small thing that is too worthless to open an issue: in new version there are new `sunscribers` property on every `Route` child. Who are `sunscribers`? 🌞

**Comment by kevindurb** [comment]
@iaminstanceof that is where the callbacks for onMatch are held

**Comment by foxdonut** [comment]
@kevindurb I think what @iaminstanceof meant was `sunscribers` should be `subscribers` :wink:

**Comment by kevindurb** [comment]
@foxdonut @iaminstanceof ahahah wow sorry guys spelling mistake! Ill get right on that!

**Comment by kevindurb** [comment]
Ok i couldnt help myself :) All done! I added `pathFromRoute` as a named export seperate from the router since neither of them need to know about each other. its out in version 1.2.0 now on npm
